

# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: asciidoc pdf and html

on:
  push:
    branches: [ backup ]
  pull_request:
    branches: [ backup ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make the PDFs and HTMLs
        id: asciidoc-2-html-and-pdf
        run: |
          docker pull ghcr.io/donnels/asciidoc:main
          docker run -v "$PWD":/documents/ --name asciidoc-to-pdf ghcr.io/donnels/asciidoc:main asciidoctor-pdf -D /documents/docs *.asciidoc
          docker run -v "$PWD":/documents/ --name asciidoc-to-html ghcr.io/donnels/asciidoc:main asciidoctor -D /documents/docs *.asciidoc

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Update changes in GitHub repository
        if: steps.git-check.outputs.modified == 'true'
        run:  |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m '[automated commit] push changed files from actions'
          git push
